runtime: php55
api_version: 1

handlers:
- url: /
  script: _.php
  secure: always
  redirect_http_response_code: 301

- url: /bootstrap
  static_dir: bootstrap
  secure: always
  redirect_http_response_code: 301

- url: /images
  static_dir: images
  secure: always
  redirect_http_response_code: 301

- url: /index\.html
  static_files: index.html
  upload: index\.html
  secure: always
  redirect_http_response_code: 301

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  secure: always
  redirect_http_response_code: 301